### ISSUE TITLE
not foud kotlin-scripting-compiler-embeddable 

### ISSUE THREAD

**Issue by imtianx** [imtianx/buildSrc#2]
detail error msg:

```
Execution failed for task ':buildSrc:compileKotlin'.
> Could not resolve all files for configuration ':buildSrc:kotlinCompilerPluginClasspath'.
   > Could not find org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.3.21.
     Required by:
         project :buildSrc
   > Could not find org.jetbrains.kotlin:kotlin-sam-with-receiver:1.3.21.
     Required by:
         project :buildSrc
```

**add jcenter**

```
repositories {
    jcenter()
}
```

ref : https://github.com/gradle/kotlin-dsl-samples/issues/1033#issuecomment-412435826

**Comment by RustamSitdikov** [comment]
the same

**Comment by imtianx** [comment]
> the same

I haven't used it for a long time, so I suggest changing to other methods, such as custom gradle plugin.

**Comment by imtianx** [comment]
Jcenter will be closed and remove all depencies. You could use `includeBuild`. 

Simple:

1. import module : `versions`
2. add to `setting.gradle`
  ```
	includeBuild("versions")
  ```
3. Depend on the plugin in the `build.gradle` of the module that needs to be used 
 ```
 plugins {
    id 'cn.imtianx.android.versions.plugin'
 }

  dependencies {
    implementation Versions.Kotlin.kotlinStdLib
    // ...
  }

 ```

[versions.zip](https://github.com/imtianx/buildSrc/blob/master/versions.zip)
